imports:
    - { resource: tables.yml }

services:
    paul999.ajaxshoutbox.listener:
        class: paul999\ajaxshoutbox\event\shoutbox_listener
        arguments:
            - @user
            - @template
            - @controller.helper
            - @auth
        tags:
            - { name: event.listener }

    paul999.ajaxshoutbox.push:
            class: paul999\ajaxshoutbox\actions\push
            arguments:
                - @config
                - @user
                - @log

    paul999.ajaxshoutbox.delete:
        class: paul999\ajaxshoutbox\actions\delete
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @log
            - @request
            - @user
            - @paul999.ajaxshoutbox.push
            - %paul999.ajaxshoutbox.tables.ajaxshoutbox%

    paul999.ajaxshoutbox.controller:
        class: paul999\ajaxshoutbox\controller\main_controller
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - @request
            - @dbal.conn
            - @auth
            - @log
            - @paul999.ajaxshoutbox.delete
            - @paul999.ajaxshoutbox.push
            - %core.root_path%
            - %core.php_ext%
            - %paul999.ajaxshoutbox.tables.ajaxshoutbox%
            - %tables.users%
